//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace landmarkRemark.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class landmarkEntities : DbContext
    {
        public landmarkEntities()
            : base("name=landmarkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<landmark> landmarks { get; set; }
    
        public virtual int ClearAndSeedData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearAndSeedData");
        }
    }
}
