//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace landmarkRemark.Models
{
    using System;
    using System.Collections.Generic;

    public partial class landmark
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public string userName { get; set; }
        public string note { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }

        public virtual User User { get; set; }
    }
}